### PR TITLE
 feat(metric): 🌟 add WAVE metric and test

### PR DESCRIPTION
**Pull request by kargaranamir**
Hi Markku,

I moved the WAVE metric to aim2.
I did not run it on the 500 most popular Alexa UIs, but I added edge test cases.

### CODE REVIEW

**Comment by mplaine** [comment]
Oh wow, thanks Amir! I will have a look at your implementation when I have more time.

In the meanwhile, if you want to continue porting existing/legacy metrics from AIM v1 to AIM v2, then please check "Static Clusters" and "Dynamic Clusters" next.

**Comment by kargaranamir** [comment]
@mplaine WAVE is ready.

**Comment by kargaranamir** [comment]
The final touches to the WAVE are as follows: 
- add more comments and hint types: done
- add one more edge test case: done
- update ranges in metrics.json: done

**Comment by mplaine** [comment]
Check the source for the color constants values and add a reference/link. Further, add names of the colors if available in the paper to improve code readability.

**Comment by mplaine** [comment]
* Add a comment about the distance and zero weight

**Comment by kargaranamir** [comment]
TODO:
- [x] Check legacy code again for the same behavior: **same with 4 decimal places**
- [x] Check [metrics.js](https://github.com/aalto-ui/aim/blob/master/aim_frontend/src/config/metrics.js) from legacy for evidence and relevance
- [x] Link to Private constants
- [x] Name colors for more readability
- [x] Add a comment on how the mean of wave scores computed

**Pull request merged**
