### PR TITLE
Feat/subband entropy

### PR DESCRIPTION
**Pull request by kargaranamir**
This pull request is created to merge the feat/subband_entopry branch with aim2.

### CODE REVIEW

**Comment by mplaine** [comment]
Hi Amir,

Thanks for the submission of this new metric. I reviewed the code you have committed. Please, find my comments below:

1. Use Python type hints with variables and functions as much as possible to catch possible runtime bugs and to improve code readability. Especially in the m7_subband_entropy.py file. See https://docs.python.org/3/library/typing.html
2. Install and use pre-commit (see README.md) that will unify coding style automatically and check for possible errors.
3. Fix any errors reported by Mypy (see README.md)
4. Fix any warnings reported by Pytest (see README.md)
5. I am not familiar with the metric, but try to cover different edge cases with your tests. You can create and add new test images, if needed.
6. In addition to documenting the return type (use type hints) of m7, please also specify the range of return values. For example, Subband entropy (float, [0, +inf]) if correct.
7. What's the magic value of 0.008 in line 162 of m7_subband_entropy.py? Move it to private constants
8. Add documentation to all methods in image_visual_clutter_utils.py. Unify the format with image_utils.py.
9. I assigned m7 to the 'Perceptual Fluency' category. Is that correct?
10. Run Evaluator App (see README.md) to generated updated results.csv and quantiles.csv files. Copy results.csv to the /frontend/src/assets/ folder.
11. Fix all score data for m7 in metrics.json. You can get range values from quantiles.csv (see above).
12. Ensure that the metric is visible and works in the GUI when run using Docker.

**Comment by kargaranamir** [comment]
1. Done.
2. Done.
3. Test files contain a warning due to "pyrtools". i opened an [issue](https://github.com/LabForComputationalVision/pyrtools/issues/11) in their code. 
4. Done.
5. I add black.png to test file. 
6. Done.
7. Done.
8. Done.
9. Yes.
10. I ran evaluator just to see if it works fine. I generate the histogram and moving it to histograms path.
11. I have the rates, i will add them after checking with you and others.

**Comment by kargaranamir** [comment]
11. Done.

**Comment by mplaine** [comment]
Hi Amir, I updated dependencies, documentation, and evaluation results. See the commit changes above.

1) Could you fix or report this other `pyrtools` warning as well, which is shown when you run `pytest .`.

```
../../../../.local/share/virtualenvs/backend-idCl-4aN/lib/python3.7/site-packages/pyrtools/tools/display.py:10
  /Users/mplaine/.local/share/virtualenvs/backend-idCl-4aN/lib/python3.7/site-packages/pyrtools/tools/display.py:10: UserWarning: Unable to import IPython.display.HTML, animshow must be called with as_html5=False
    warnings.warn("Unable to import IPython.display.HTML, animshow must be called with "
```

2) Are the unit tests for the metric `m7` comprehensive enough, at least for now?


3) The following error message is shown in the browser's console upon the execution of Subband entropy in dockerless mode. Any idea why this happens and how to fix it?

```
TypeError: Cannot read properties of undefined (reading '0')
    at eval (RecordedResultsChart.js?2b68:36)
```

4) Docker fails to install the web app due to the following error (again related to `pyrtools`). Any idea why this happens and how to fix it?

```
#21 163.1     building 'pyrtools.pyramids.c.wrapConv' extension
#21 163.1     creating build/temp.linux-x86_64-3.8
#21 163.1     creating build/temp.linux-x86_64-3.8/pyrtools
#21 163.1     creating build/temp.linux-x86_64-3.8/pyrtools/pyramids
#21 163.1     creating build/temp.linux-x86_64-3.8/pyrtools/pyramids/c
#21 163.1     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.8 -c pyrtools/pyramids/c/convolve.c -o build/temp.linux-x86_64-3.8/pyrtools/pyramids/c/convolve.o -fPIC -shared
#21 163.1     unable to execute 'gcc': No such file or directory
#21 163.1     error: command 'gcc' failed with exit status 1
#21 163.1     ----------------------------------------
#21 163.1 ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5makg467/pyrtools_535a13cc9b2848ddbd672bbbbc85f402/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5makg467/pyrtools_535a13cc9b2848ddbd672bbbbc85f402/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xolk7y99/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/pyrtools Check the logs for full command output.
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c export DEBIAN_FRONTEND=noninteractive   && apt-get update   && apt-get install -y --no-install-recommends wget unzip gnupg2   libglib2.0-0 libnss3 libgconf-2-4 libxcb1 libfontconfig1 xvfb   && useradd --system -s /sbin/nologin aim   && mkdir -p /home/aim   && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -   && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list   && apt-get update -qqy   && apt-get -qqy install ${CHROME_VERSION:-google-chrome-stable}   && rm /etc/apt/sources.list.d/google-chrome.list   && python -m pip install --no-cache-dir --upgrade pip   && pip install --no-cache-dir -r requirements.txt   && VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)   && wget -q "https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_linux64.zip" -O driver.zip   && unzip driver.zip   && chmod +x chromedriver   && mkdir -p webdrivers   && mv chromedriver ./webdrivers/chromedriver_linux   && apt-get remove --purge -y --auto-remove unzip gnupg2   && apt-get clean   && chown -R aim .   && chown -R aim ../metrics.json   && chown -R aim /home/aim   && rm -rf driver.zip /etc/apt/sources.list.d/google-chrome.list /var/lib/apt/lists/* /var/cache/apt/*]: exit code: 1
```

**Comment by kargaranamir** [comment]
1. I will check it. I think I know what I should [do](https://github.com/LabForComputationalVision/pyrtools#dependencies). 
2. Yes, at least for now. Also, I checked all of 500  Alexa images with the original author's Matlab code and got the same result with 0.01 absolute error. 
3. related to the issue number 4?
4. it seems the `gcc` is not installed. according to the [documentation](https://pyrtools.readthedocs.io/en/latest/installation.html)  it needs `gcc` version >= 6 in order for the C code to compile. Also, as I said before this package doesn't work on Windows because of the same matter (`gcc` isn't necessarily [installed](https://github.com/LabForComputationalVision/pyrtools#installation)).

**Comment by mplaine** [comment]
1. I committed a fix. Thanks for the link!
2. That's great to hear! No need for further actions.
3. Unrelated. I will have a look at this today. It could be related to bad values, file formatting, or a bug in the code. In case of the latter, I will ask whether Valentin would have time to look at it as he has written that part of the code.
4. Thanks for the links. I will look at this today as well. I will contact Valentin (our Docker expert), if needed.

**Comment by mplaine** [comment]
4. Fixed now

**Comment by mplaine** [comment]
@vanntile Would you have time to look at issue #3 above? I get the following error in the browser's console when the execution of the 'Subband entropy' metric (m7) completes. `results.json` and `metrics.json` should both be fine so I am leaning towards a bug in `RecordedResultsChart.js` / `Results.vue`.

Here is the error message:
```
vue.esm.js?a026:628 [Vue warn]: Error in updated hook: "TypeError: Cannot read properties of undefined (reading '0')"

found in

---> <Results> at src/components/Results.vue
       <AIMForm> at src/components/AIMForm.vue
         <App> at src/App.vue
           <Root>
warn @ vue.esm.js?a026:628
logError @ vue.esm.js?a026:1902
globalHandleError @ vue.esm.js?a026:1897
handleError @ vue.esm.js?a026:1857
invokeWithErrorHandling @ vue.esm.js?a026:1880
callHook @ vue.esm.js?a026:4244
callUpdatedHooks @ vue.esm.js?a026:4376
flushSchedulerQueue @ vue.esm.js?a026:4361
eval @ vue.esm.js?a026:1998
flushCallbacks @ vue.esm.js?a026:1924
Promise.then (async)
timerFunc @ vue.esm.js?a026:1951
nextTick @ vue.esm.js?a026:2008
queueWatcher @ vue.esm.js?a026:4427
update @ vue.esm.js?a026:4569
notify @ vue.esm.js?a026:739
reactiveSetter @ vue.esm.js?a026:1064
pushResults @ index.js?58ae:101
wrappedMutationHandler @ vuex.esm.js?2f62:844
commitIterator @ vuex.esm.js?2f62:466
eval @ vuex.esm.js?2f62:465
_withCommit @ vuex.esm.js?2f62:624
commit @ vuex.esm.js?2f62:464
boundCommit @ vuex.esm.js?2f62:409
pushResults @ index.js?58ae:74
wrappedActionHandler @ vuex.esm.js?2f62:851
dispatch @ vuex.esm.js?2f62:516
boundDispatch @ vuex.esm.js?2f62:406
$socketClient.onMessage @ AIMForm.vue?2660:444
instance.onmessage @ VueSimpleWebSocket.module.js?83cf:1
vue.esm.js?a026:1906 TypeError: Cannot read properties of undefined (reading '0')
    at eval (RecordedResultsChart.js?2b68:36)
    at Array.forEach (<anonymous>)
    at fillData (RecordedResultsChart.js?2b68:26)
    at VueComponent.updated (Results.vue?82a0:171)
    at invokeWithErrorHandling (vue.esm.js?a026:1872)
    at callHook (vue.esm.js?a026:4244)
    at callUpdatedHooks (vue.esm.js?a026:4376)
    at flushSchedulerQueue (vue.esm.js?a026:4361)
    at Array.eval (vue.esm.js?a026:1998)
    at flushCallbacks (vue.esm.js?a026:1924)
```

Obviously, the histogram generation for m7 fails due to this issue.

**Comment by vanntile** [comment]
@mplaine I have found the mistake, it's in the plot generation function, it seems to appear due to a configuration of the data I was not previously expecting and a bug in the code. Will update the plot generation formulas

**Comment by mplaine** [comment]
Thanks for your help and quick fix, Valentin! Histograms work with all metrics now.

While testing the histograms with various inputs, I noticed two more minor issues related to them.

1. Your score is sometimes associated with a wrong bar. For example, the X-axis tick value on the left-hand side of the your score bar is sometimes lower than your score.
2. Your score bar is not drawn at all if it falls into the last bucket and is less than the last X-axis tick value. Related to the above, I assume.

I have attached two screenshots (inputs) and their associated metric (contour congestion) results to illustrate and reproduce the issues. airbnb.com for issue #1 and aalto.fi for issue #2.
[test_files.zip](https://github.com/aalto-ui/aim/files/7230792/test_files.zip)

Let me know if you need help in testing or further explanation of the issues.

**Comment by vanntile** [comment]
For both of the above issues. The x-ticks are rounded (up as I recall) and the value of your result isn't, this being the source of the discrepancy. The plotting is in fact correct, it's just that if you want to round the x-ticks values, this might be the result. A fix for it is not obvious and would literally try to make it "wrong".

For the second issue. Again, I think the plot is correct, just that the last bar doesn't have any meaningful height as it only has our result (a small enough frequency to be invisible).

**Comment by mplaine** [comment]
`intl.format(...)` rounds to the closest decimal (down or up). I unified the way how all values shown in histograms are rounded. IMO, values shown in the resulting histograms are now more logical. I tested this with several inputs.

@vanntile What's your opinion, and did I miss any lines that should be edited as well?

**Comment by vanntile** [comment]
@mplaine Checked it myself. LGTM

**Comment by mplaine** [comment]
Thanks for your help Amir and Valentin! The branch has been merged to 'aim2' and I deleted this feature branch.

**Comment by kargaranamir** [comment]
Thank you both. @mplaine If you have time please take a look at feature congestion [pull request](https://github.com/aalto-ui/aim/pull/22). I remember we could not have both scalar and image output metrics together because of `visualizationType` in 'metrics.josn'. As a result, I just return the scalar one.

**Pull request merged**
