### PR TITLE
Dockerize AIM frontend and backend

### PR DESCRIPTION
**Pull request by vanntile**
Make development and trying the AIM app by add Docker build files and Compose files for quick development.
Change the configurations to a new environment-variables based system.

### CODE REVIEW

**Comment by mplaine** [comment]
Thanks for the PR! I reviewed and tested the code. I also updated README and other documentation.

A couple of issues that I found while testing the web app:
1. Database - MongoDB Express works only with the default host and port (localhost:27017).
2. Database - The server was unable to connect to the database in Docker-less mode
3. Frontend - Dynamic chart is not rendered if you select only one metric to be evaluated.
4. Backend - mypy gives three errors (lines 90, 92, 94 in server.py)

Would you have time to fix the above issues, and possibly test the code?

**Comment by vanntile** [comment]
Addressing the fours issues:
1. According to the Mongo Express [Docker Hub page](https://hub.docker.com/_/mongo-express), you can set the port of the Mongo Database
2. Can you offer a more accurate case description? For me it seems to be working. With the webdrivers present and changing the host and port of the database, it seems to be working.
3. I don't think that is a proper description of the bug, as far as I can test for it, I can see it also happens when you have two metrics selected. We first need to detect the actual behavior, then I will patch.
4. I have pushed a fix for the typings issues

**Comment by vanntile** [comment]
My latest commit adds a Vue lifecycle hook that should fix the frontend issue. As far as I seem to understand it, it won't trigger the plotting of data for the first response it gets from the backend (and when that is the only response, it won't display anything at all). The update should fix it

**Comment by mplaine** [comment]
Issues #2-4 have been fixed. I will look at the issue #1 next.

**Comment by mplaine** [comment]
My latest commit binds MongoDB to the given port and exposes that port for potential MongoDB clients, such as Robo 3T and MongoDB Compass. AIM backend and MongoDB Express connect to the same port.

**Pull request merged**
