### PR TITLE
Feat/feature congestion

### PR DESCRIPTION
**Pull request by kargaranamir**
This pull request is created to merge the feat/feature_congestion branch with aim2.

### CODE REVIEW

**Comment by kargaranamir** [comment]
The code was also improved using feat/subband_entropy comments.

**Comment by mplaine** [comment]
Hi Amir! Yes, I plan to review this metric as soon as possible.

**Comment by mplaine** [comment]
Thanks for your contribution, Amir! I reviewed the code and updated the documentation here and there. Please, find my comments below:

1. m8_feature_congestion.py, line 115: Which value is correct: 0.001 or 0.000001?
```
_ORIENT_NOISE: float = 0.001  # Was eps, but that gave too much orientation noise in the saliency maps. Then changed to 0.000001
```
2. m8_feature_congestion.py, line 154: What are these magic numbers, any idea?
```
kernel_1d: np.ndarray = np.array([[0.05, 0.25, 0.4, 0.25, 0.05]])
```
3. m8_feature_congestion.py, line 499: Is this range correct?
```
- Feature congestion (float, [0, +inf))
```
4. m8_feature_congestion.py, line 539: Add an explaining comment above this code section
```
clutter_scalar_fc: float = float(
```
5. Again, try to cover different edge cases with your tests. Did you compare the results of this implementation against the ones produced by the original Matlab implementation? All good?

**Comment by kargaranamir** [comment]
Hi Markku, thanks again for revising my code. 
1. Most of the comments in the code are not mine and I just keep them as official paper code and don't know what should I do in a situation like this. I will try to figure out what is right and will edit it. 
2. These magic numbers are an approximation for the five-tap 1D Gaussian filter, (see [here](http://www.johncostella.com/magic/), [here](http://www.cs.toronto.edu/~mangas/teaching/320/assignments/a3/tcomm83.pdf), and [here](http://users.utcluj.ro/~tmarita/HCI/C7-8-extra/Pyramids/RCA84.pdf)). Also, I used them in the `backend/aim/common/image_visual_clutter_utils.py` as a default kernel. Should I move them to private constants?
3. Yes!
4. Sure.
5. I tried one time and did not find any special edge cases, but I will check them again. Also, I ran 100/500 pictures and found the results similar with 0.1 absolute error, but we know why we have this much difference. For example, the `imrotate` function (image rotation with the interpolation) in our code is a little different from Matlab's `imrotate` function (from the image processing toolkit) but it is the most similar one and that's why we use the `scikit image` library. I explained it in the group meeting (back to my first presentation) and we concluded that this much difference is fine.

**Comment by mplaine** [comment]
1. I thought this might have been the case. Could you add a comment somewhere in the file, where the original Matlab implementation can be found. Something like. "Based on XXX's Matlab implementation available at YYY"
2. Please, do that or add a comment next to it.
3. OK
4. OK
5. I agree, this accuracy is close enough.

**Comment by mplaine** [comment]
Hi Amir,
what's the status of final changes?

**Comment by kargaranamir** [comment]
Hi,
Sorry, I just changed my laptop. I will commit the changes asap.

**Comment by kargaranamir** [comment]
Hi Markku, 

1. I added the Matlab code as a reference comment in the metric class and also edited the comment line. 
2. I added a comment for it, but I did not move to the private constants because I think in this case it is better to keep the code as much as possible similar to the Matlab code for better troubleshooting. 
3. I tried different images in Matlab code and couldn't find any value less than ~ 1.2483
4. Done.
5. I tried different images as well in the previous days and added some other test cases.

**Comment by mplaine** [comment]
The Feature congestion metric (m8) is ready. Big thanks for your contribution, Amir!

**Pull request merged**
