### PR TITLE
Feat/m8 with visualizations

### PR DESCRIPTION
**Pull request by kargaranamir**
Hi @mplaine,
Please review this pull request: I added output image of m8 and updated `metrics.json` as well.
The output image is in grayscale mode and normalized between 0-255 (same as Matlab code).

### CODE REVIEW

**Comment by mplaine** [comment]
Hi @kargaranamir ! Big thanks for the PR!

I refactored your code a bit and merged it with the latest code in `aim2`.

Could you kindly test that everything still works as expected? Furthermore, could you add a couple of unit tests for image results? See `test_m9.py` for an example.

Could you also explain to me why you use `255 / 2` as the fill value in:
`return np.full_like(arr, 255 / 2).astype("uint8")`

If all is good, I will then re-evaluate all metrics and update `results.json` and other result files.

**Comment by kargaranamir** [comment]
Thank you so much.  I will add unit tests for image results. 

The `normalize` function normalizes the values between 0 to 255 (To better show the differences), and if all of the array numbers are equal, should converts the values to the midvalue (255/2~127). This was the result of my experience working with MATLAB code.

**Comment by mplaine** [comment]
If possible, try to find and use original inputs for unit tests so that we can compare the results against the ones in the publication/project page.

**Comment by mplaine** [comment]
Hey @kargaranamir ! Any progress regarding the unit tests? Can I help you somehow?

**Comment by kargaranamir** [comment]
Hi @mplaine, 
I was a little busy with my university assignments. Thanks for reminding me, I will make the changes asap.

**Comment by kargaranamir** [comment]
Hi @mplaine, 
I was a little busy with my university assignments. Thanks for remining me, i will make the changes asap.

**Comment by kargaranamir** [comment]
Hi @mplaine, sorry for the delay. I checked the [Measuring Visual Clutter](https://jov.arvojournals.org/article.aspx?articleid=2122001) paper, and select [map.png](https://github.com/aalto-ui/aim/blob/feat/m8-with-visualizations/backend/data/tests/map.png) as an original input. 
Also, the high-quality map.png (actuality its format is jpg, i converted it to png) was available as the only test image in the [author's source code files](https://dspace.mit.edu/handle/1721.1/37593).

I edited the test_m8.py for the map.png with both scalar and visualization expected results. The test file becomes heavy if we want to add all visualization outputs for each test, so I kept the previous test cases as before.

**Comment by mplaine** [comment]
Thanks @kargaranamir ! I will review and test your changes next week at the latest.

**Comment by mplaine** [comment]
Looks and works perfectly! Thanks @kargaranamir !

**Pull request merged**
