### PR TITLE
Feat: new perceptual metric: MDEAM

### PR DESCRIPTION
**Pull request by MarcWong**
MDEAM (Multi-duration Element Attention Model)

Description:
The predicted human attention under three viewing durations, visualized as heatmaps of three durations (0.5, 3, and 5 seconds).

Publication:
Y. Wang, M. Bâce and A. Bulling, "Scanpath Prediction on Information Visualisations," in IEEE Transactions on Visualization and Computer Graphics. doi: 10.1109/TVCG.2023.3242293

### CODE REVIEW

**Comment by mplaine** [comment]
Thanks Yao! I had a quick first look at your PR. Could you kindly apply the following changes before we can proceed:
1. **tests/metrics/test_m30.py:** change references from UMSI to MDEAM
2. **aim/metrics/m30/*.py:** add typing hints to improve maintainability
3. **CONTRIBUTING.md:** compute metric results and update contributors by following the instructions after the tables
4. **CONTRIBUTING.md:** run the utility tools and tests to lint and test your code

**Comment by MarcWong** [comment]
all requirements applied in my latest commit.

=========================================== test session starts ============================================
platform linux -- Python 3.7.16, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /netpool/homes/wangyo/.conda/envs/aim2/bin/python
cachedir: .pytest_cache
rootdir: /netpool/homes/wangyo/Projects/aim/backend, configfile: pytest.ini
collected 2 items                                                                                          

tests/metrics/test_m30.py::test_mdeam_desktop[aalto.fi_website.png-expected_results0] PASSED
tests/metrics/test_m30.py::test_mdeam_desktop[myhelsinki.fi_website.png-expected_results1] PASSED

============================================ 2 passed in 16.20s ============================================

**Comment by mplaine** [comment]
Could you please address #3 re metric results by following these instructions?

Screenshot 2023-06-08 at 16 19 03

**Comment by MarcWong** [comment]
If I run `python evaluator.py -m m30 -o data/evaluations/ALEXA_500 -p`

then it goes like:
```
/netpool/homes/wangyo/.conda/envs/aim2/lib/python3.7/site-packages/skimage/segmentation/random_walker_segmentation.py:49: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if Version(scipy.__version__) >= Version('1.1'):
The directory 'data/evaluations/ALEXA_500' already exists. Delete existing files before continuing? [y/N] 
2023-06-08T14:34:36.973Z | INFO     | aim.common.utils:show_header:45 | Evaluator 1.1
2023-06-08T14:34:36.973Z | INFO     | aim.common.utils:show_header:46 | =============
2023-06-08T14:34:36.973Z | INFO     | aim.common.utils:show_header:47 | 
2023-06-08T14:34:36.974Z | INFO     | __main__:main:130 | Evaluate screenshots stored at 'data/screenshots/ALEXA_500'.
2023-06-08T14:34:37.009Z | INFO     | __main__:main:139 | 427 out of 427 screenshots were successfully evaluated and the results were stored at 'data/evaluations/ALEXA_500'.

```

and nothing was generated...

Instead, I executed:
`python evaluator.py -m m30 -i data/screenshots/ALEXA_500/ -p -o data/evaluations/results/`

and updated the results into `data/evaluations/ALEXA_500/quantiles.csv` and `data/evaluations/ALEXA_500/results.csv` manually.

Please let me know if further actions should be taken.

**Comment by mplaine** [comment]
Merged the "m30" metric into a dedicated feature branch in the AIM repository.

**Pull request merged**
