### PR TITLE
feat(metric, segmentation): segmentation and grid metrics

### PR DESCRIPTION
**Pull request by kargaranamir**
- [x] Segmentation 
- [x] Grid Metrics

### CODE REVIEW

**Comment by kargaranamir** [comment]
- [x] (somehow done) ~~Move (and Adjust) parameters from segmentation to constants~~
- [x] (no need) ~~Add comments and types: some of the segmentation parts doesn't have proper comment and type~~
- [x] Add documentation for segmentation output 
- [x] (no need) ~~Add CNN Rico model using LFS~~
- [x] Design proper test cases for grid metrics (we have tests, I just run metrics on general UIs, we need better test cases)
- [x] Change Evaluator to compute segmentation time -> Run Evaluator
- [x] ~~Replacing segmentation output image instead of screenshot image (code)~~ 
- [x] Support run of segmentaion metrics in web core (handler)
- [x] Update Metrics.json for judgments

**Comment by mplaine** [comment]
I am leaning more and more toward combining the metrics m21-m25 (G1-G5) together into a single metric (Grid Quality as per Table 3 in CHI'15) with multiple items (G1-G5). Or should we call it _Layout Quality_ and include White Space as well?

Any thoughts on this potential refactoring?

**Comment by kargaranamir** [comment]
Though both names recommended are good, I prefer "Grid Quality" since "Layout" is a broad term.
I think each of the metrics should be maintained as a class method in the "single metric".
The metrics still need to be tested a bit more. It's definitely on my to-do list for this week.

**Comment by mplaine** [comment]
> Though both names recommended are good, I prefer "Grid Quality" since "Layout" is a broad term. I think each of the metrics should be maintained as a class method in the "single metric". The metrics still need to be tested a bit more. It's definitely on my to-do list for this week.

I agree. Let's combine G1-G5 into a single metric called _Grid quality_ as per Table 3 in CHI'15 AND leave _White space_ as it is in metric m26.

**Comment by mplaine** [comment]
Hi Amir! Are these metrics ready for review?

**Comment by kargaranamir** [comment]
G1-G5
- [x] Revise 
- [x] Test
- [x] Test case

**Comment by kargaranamir** [comment]
Hi Markku (@mplaine)!

I'm sorry it took me so long to update. I combined the G1-G5 as a single metric (+design test cases + run evaluator + update metrics.json).
From here, only the [unchecked box](https://github.com/aalto-ui/aim/pull/55#issuecomment-1227419587) remained.

Just checking with you, I believe there is no need to replace the screenshot image with the segmentation output image (in the case of metrics that need segmentation selected). The screenshot shows what we process and should not be changed. Furthermore, the segmentation algorithm we used has some errors, and when users see an error (screenshot is the first things that users see), they think the whole system is not accurate. 

Instead, I propose 3 alt: 1) let segmentation also be a metric like UMSI. 2) disregard the segmentation output image. 3) Have it as a submetric of grid quality metric, since this metric relies heavily on segmentation.

**Comment by mplaine** [comment]
Good observations and proposals. If my memory serves me right, the legacy version computed segmentation (for performance reasons) and showed the segmentation output image in Preview only if one or more selected metrics depended on segmentation. Your proposal of **always** showing a screenshot image in Preview (instead of segmentation output image) makes sense and is well argued. Further, you proposed to include the segmentation output image as submetric of the grid quality metric. My only concern is what if the user selects some other metric than grid quality that depends on segmentation. For example, white space or visual search performance (VSP). In these cases, should we **not** show the segmentation output image at all, as you suggested, or go with the legacy approach described above? White space is just a metric value so it does not necessarily have to show the segmentation output image and VSP outputs its own image with segmentated areas.

**Comment by kargaranamir** [comment]
> Good observations and proposals ...

there is also another option: Let's make segmentation an individual metric as well, so users can see how their image is segmented if select it.

**Comment by kargaranamir** [comment]
I resloved everything that was keeping you from reviewing this code. Everything worked as expected :rocket: . If you have any problems or suggestions, please let me know. It's okay if you want to move/change things, since we didn't discuss the right place of everything.

**Comment by mplaine** [comment]
I like your idea of having segmentation output image as a separate metric. Could you edit this PR to reflect that idea? I can reevaluate metrics and update metrics.json during the review process.

**Comment by kargaranamir** [comment]
> I like your idea of having segmentation output image as a separate metric. Could you edit this PR to reflect that idea? I can reevaluate metrics and update metrics.json during the review process.

done. do you want me to add the aim legacy segmentation as another metric as well?

**Comment by mplaine** [comment]
> done. do you want me to add the aim legacy segmentation as another metric as well?

👏 Yeah, that's a good idea!

**Comment by kargaranamir** [comment]
> 👏 Yeah, that's a good idea!

done.

**Comment by mplaine** [comment]
Where do you recommend these new metrics to be placed? They have not been assigned to any categories in `metrics.json`.

**Comment by kargaranamir** [comment]
Hi, The closest category to these metrics seems to be perceptual fluency.

**Comment by mplaine** [comment]
Thank you so much Amir for this massive contribution!!! I am finally done with reviewing and merging the code. Sorry about the delay. I am currently evaluating all metrics so that I can update all result JSON files. Once I am done with it I can deploy a new version to the production server.

Q: `docker-compose up --build` does not seem to be working anymore. Does it work on your computer, and if yes, could you share your `requirements.txt` file?

**Comment by kargaranamir** [comment]
Hi Markku, It is much appreciated. However, I am currently not able to use docker due to some issues with the M1 architecture. The only thing I have now is a pip freeze of my environment, I'm not sure if that helps. file: [pip_req_freeze.txt](https://github.com/aalto-ui/aim/files/10280473/pip_req_freeze.txt)

**Pull request merged**
