### PR TITLE
Feat/clusters

### PR DESCRIPTION
**Pull request by kargaranamir**
Hi, I have refactored clusters' legacy code. There are, however, a few things I think could be improved, especially for the dynamic clustering.

### CODE REVIEW

**Comment by mplaine** [comment]
Thanks Amir! Could you also include CV3 (CHI 2015) to this set of metrics as it is highly related?

**Comment by kargaranamir** [comment]
The legacy implementation of Dynamic clusters reports 2 scores.
1. m12_0: the Number of Dynamic Clusters (CV5)
2. m12_1: The Average Colors Per Cluster (CV3)
We have it already in the code. However, since the dynamic cluster does not have a fast implementation I will suggest that we keep the legacy code as-is and don't separate them.

**Comment by kargaranamir** [comment]
Cluster metrics are now available.
Running the legacy code, I find no difference in the behavior of the new code.

**Comment by mplaine** [comment]
* Make the distance value as a constant
* Make a note about the used order for clustering (which matters the results)
* Replace TODOs in metrics.json
* Import dynamic clusters into the average number of colors per cluster metric

**Comment by kargaranamir** [comment]
- [x] Metrics.json

**Comment by mplaine** [comment]
- I updated metric descriptions for m11 and m12 (+minor code changes)
- The logic in m11 may not be correct anymore after my changes (final steps of the implementation)
- Color threshold vs cluster threshold in m12
- "Only clusters containing more than 5 values are counted" may be inccorect (m11 and m12)
- Let's discuss how these metrics should be interpreted based on the papers, and change the implementations accordingly, if needed

**Pull request merged**
